# see https://circleci.com/docs/2.0/language-javascript/

version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: circleci/node:8.12

    working_directory: ~/md-to-pdf

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}

      - run: npm install

      - run: npm install tap-xunit --no-save

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: make test-results dirs
          command: mkdir -p ~/test-results/xo ~/test-results/ava

      - run:
          name: lint
          command: npx xo --reporter junit > ~/test-results/xo/results.xml

      - run:
          name: test
          command: npx ava --tap | npx tap-xunit > ~/test-results/ava/results.xml

      - store_test_results:
          path: ~/test-results
